### ISSUE TITLE
needs update for string.data changes

### ISSUE THREAD

**Issue by stevengj** [JuliaStrings/LegacyStrings.jl#11]
After JuliaLang/julia#19449, soon to be merged for Julia 0.6, you will no longer be able to access the raw bytes of a string via `string.data`; instead, do `Vector{UInt8}(string)`.  For example, this affects:

https://github.com/JuliaArchive/LegacyStrings.jl/blob/d96e96adadd7cec0ddfe2342d1929a5a972247a2/src/ascii.jl#L100

**Comment by matthias314** [comment]
At least the example is already fixed by #29.

**Comment by stevengj** [comment]
Yes, this issue can be closed.
