### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by crstnbr** [JuliaStrings/LegacyStrings.jl#37]
After https://github.com/JuliaStrings/LegacyStrings.jl/pull/36 it would be useful to have a new release tagged. This would reduce warnings when precompiling packages that depend on LegacyStrings, like JLD, on 1.0.

Is this possible?

**Comment by nalimilan** [comment]
Sure. See https://github.com/JuliaLang/METADATA.jl/pull/19964.

**Comment by crstnbr** [comment]
Thanks.
