### ISSUE TITLE
Is it possible to construct a UTF32String from an Array{Char, 1}?

### ISSUE THREAD

**Issue by x-ji** [JuliaStrings/LegacyStrings.jl#38]
From the error prompt from my REPL I thought it would be possible to construct a UTF32String from Array{Char, 1}. However, when I try to do so, I get

```
julia> t = "asdf"
"asdf"

julia> c = Vector{Char}(t)
4-element Array{Char,1}:
 'a'
 's'
 'd'
 'f'

julia> UTF32String(c)

ERROR: MethodError: no method matching UTF32String(::Base.ReinterpretArray{UInt32,1,Char,Array{Char,1}})
Closest candidates are:
  UTF32String(::Array{UInt32,1}) at /home/jx/.julia/packages/LegacyStrings/tkVHE/src/LegacyStrings.jl:96
  UTF32String(::Array{Char,1}) at /home/jx/.julia/packages/LegacyStrings/tkVHE/src/utf32.jl:3
Stacktrace:
 [1] UTF32String(::Array{Char,1}) at /home/jx/.julia/packages/LegacyStrings/tkVHE/src/utf32.jl:3
 [2] top-level scope at none:0
```

which is weird to me since the second candidate literally says `UTF32String(::Array{Char,1})`.

Is the only way to construct a UTF32String via `utf32(s)`?

**Comment by nalimilan** [comment]
The bug is inside the `UTF32String(::Array{Char,1})` method. It's probably due to changes to `reinterpret` which have happened since Julia 0.6. Shouldn't be too hard to fix you want to give it a try.

**Comment by stevengj** [comment]
It can't be done with `reinterpret` because the `Char` representation in Julia 1.0 is *not* equivalent to UTF-32.  We'll just need to add a method like:
```jl
UTF32String(c::AbstractVector{<:AbstractChar}) = UTF32String([UInt32(c) for c in c])
```
