### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by grero** [JuliaStrings/LegacyStrings.jl#41]
Would it be possible to create a new release? I just ran into an issue where the Compats requirements in the previous release was preventing other packages from being updated, in particular Optim. Using the latest master solved the issue, but it would be nice to have to rely on that. Thanks!

**Comment by stevengj** [comment]
Will be fixed by https://github.com/JuliaRegistries/General/pull/21448

**Comment by grero** [comment]
Great, thanks!
