### ISSUE TITLE
ambiguous three-argument nextind for DirectIndexString

### ISSUE THREAD

**Issue by knuesel** [JuliaStrings/LegacyStrings.jl#52]
It seems that LegacyStrings is missing a `nextind` definition:

```julia
julia> str = ASCIIString(zeros(10))
"\0\0\0\0\0\0\0\0\0\0"

julia> str = ASCIIString(zeros(1000))
Error showing value of type ASCIIString:
ERROR: MethodError: nextind(::ASCIIString, ::Int64, ::Int64) is ambiguous.
```

**Comment by stevengj** [comment]
It has `nextind` here: https://github.com/JuliaStrings/LegacyStrings.jl/blob/8d9fd731767d4c86c7b71210b259d45045840d9c/src/directindex.jl#L11-L24

but apparently it is missing a more specialized method, making the function ambiguous.
